# Generated by Django 4.1.4 on 2023-01-02 13:12

from django.db import migrations, models
import polls.my_vals


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=400, validators=[polls.my_vals.validate_question]),
        ),
    ]
